---
abstract: "Business::CPI's PagSeguro driver"
author:
  - 'André Walker <andre@andrewalker.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CPI-Gateway-PagSeguro
requires:
  Business::CPI: 0.1
  DateTime: 0
  LWP::Simple: 0
  Moo: 0
  URI: 0
  XML::LibXML: 0
resources:
  repository: git://github.com/andrewalker/p5-business-cpi-gateway-pagseguro.git
version: 0.3
